# Generated by Django 4.0.1 on 2022-02-01 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='verify_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=355)),
                ('company_name', models.CharField(max_length=255)),
                ('calls_remaining', models.IntegerField(verbose_name='Количество оставшихся звонков')),
                ('exp', models.DateField(default=datetime.date(2022, 7, 31), verbose_name='звонки активны до:')),
            ],
        ),
    ]
