# Generated by Django 4.0.1 on 2022-02-01 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verify_number',
            options={'verbose_name': 'Верификация', 'verbose_name_plural': 'Верификации'},
        ),
        migrations.RemoveField(
            model_name='verify_number',
            name='company_name',
        ),
        migrations.AddField(
            model_name='verify_number',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='компания'),
        ),
    ]
