# Generated by Django 4.0.1 on 2022-02-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_verify_number_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='verify_number',
        ),
    ]
