# Generated by Django 4.0.1 on 2022-02-04 11:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='verify_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=355)),
                ('calls_remaining', models.IntegerField(verbose_name='Количество оставшихся звонков')),
                ('exp', models.DateField(default=datetime.date(2022, 8, 3), verbose_name='звонки активны до:')),
                ('user', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='компания')),
            ],
            options={
                'verbose_name': 'Данные о звонках',
                'verbose_name_plural': 'Данные о звоноках',
            },
        ),
        migrations.CreateModel(
            name='MakeCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_token', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='компания')),
            ],
            options={
                'verbose_name': 'Данные о звонках',
                'verbose_name_plural': 'Данные о звоноках',
            },
        ),
    ]
