# Generated by Django 4.0.1 on 2022-02-07 05:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='makecall',
            options={'verbose_name': 'Данные запроса звонка', 'verbose_name_plural': 'Данные запроса звонков'},
        ),
        migrations.AlterField(
            model_name='verify_number',
            name='exp',
            field=models.DateField(default=datetime.date(2022, 8, 6), verbose_name='звонки активны до:'),
        ),
        migrations.CreateModel(
            name='calls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_number', models.CharField(max_length=15)),
                ('verify_number', models.CharField(max_length=15)),
                ('call_date', models.DateTimeField(verbose_name=datetime.datetime(2022, 2, 7, 5, 18, 8, 897521))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='компания')),
            ],
        ),
    ]
