# Generated by Django 4.0.1 on 2022-02-08 04:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verify', '0002_alter_makecall_options_alter_verify_number_exp_calls'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_number', models.CharField(max_length=15, verbose_name='исходящий номер')),
                ('verify_number', models.CharField(max_length=15, verbose_name='проверочный номер')),
                ('call_date', models.DateTimeField(default=datetime.datetime(2022, 2, 8, 9, 1, 1, 690759), verbose_name='Дата и время вызова')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='компания')),
            ],
            options={
                'verbose_name': 'История вызовов',
                'verbose_name_plural': 'История вызовов',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=355)),
                ('calls_remaining', models.IntegerField(verbose_name='Количество оставшихся звонков')),
                ('balance', models.IntegerField(verbose_name='Остаток на балансе')),
                ('coast_call', models.IntegerField(verbose_name='Стоимость звонка')),
                ('exp', models.DateField(default=datetime.date(2022, 8, 7), verbose_name='звонки активны до:')),
                ('user', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='компания')),
            ],
            options={
                'verbose_name': 'Данные о звонках',
                'verbose_name_plural': 'Данные о звоноках',
            },
        ),
        migrations.RemoveField(
            model_name='verify_number',
            name='user',
        ),
        migrations.DeleteModel(
            name='calls',
        ),
        migrations.DeleteModel(
            name='verify_number',
        ),
    ]
