# Generated by Django 4.0.1 on 2022-02-08 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0003_usercalls_userinfo_remove_verify_number_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercalls',
            options={'verbose_name': 'История звонков', 'verbose_name_plural': 'История звонков'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'Данные пользователя', 'verbose_name_plural': 'Данные пользователей'},
        ),
        migrations.AddField(
            model_name='usercalls',
            name='coast',
            field=models.FloatField(default=0.35, verbose_name='стоимость звонка руб.'),
        ),
        migrations.AlterField(
            model_name='usercalls',
            name='call_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 8, 11, 27, 4, 326957), verbose_name='Дата и время вызова'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='balance',
            field=models.FloatField(default=100, verbose_name='Остаток на балансе руб.'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='coast_call',
            field=models.FloatField(default=0.35, verbose_name='Стоимость звонка руб.'),
        ),
    ]
