# Generated by Django 3.2.12 on 2022-03-15 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0004_alter_usercalls_options_alter_userinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercalls',
            name='call_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 9, 35, 49, 283226), verbose_name='Дата и время вызова'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='calls_remaining',
            field=models.IntegerField(default=30, verbose_name='Количество оставшихся звонков'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='coast_call',
            field=models.FloatField(default=0.3, verbose_name='Стоимость звонка руб.'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='exp',
            field=models.DateField(default=datetime.date(2022, 9, 11), verbose_name='звонки активны до:'),
        ),
    ]
